version: '3.9'

services:
  project3:
    build:
      context: .
    working_dir: /app/TodoApp
    ports:
      - "9999:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/TodoApp
